const dotenv = require('dotenv')
dotenv.config()

const { PORT, DB_URL, ACCESS_TOKEN, CORS_ORIGIN_URL, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET } = process.env

module.exports = { PORT, DB_URL, ACCESS_TOKEN, CORS_ORIGIN_URL, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET }